### ISSUE TITLE
Feature: 인게임 연출을 강화한다.

### ISSUE THREAD

**Issue by ParkHyeonJae** [ParkHyeonJae/Isolate-Island#68]

**Comment by LalDi** [comment]
게임 시작할 때 쓰러져있다가 일어나는 애니메이션 추가 부탁드립니다
Dead 애니메이션 역재생 하는 모션으로 바람

**Comment by ParkHyeonJae** [comment]
> 게임 시작할 때 쓰러져있다가 일어나는 애니메이션 추가 부탁드립니다
> Dead 애니메이션 역재생 하는 모션으로 바람
